network:
  ethernets:
    enp1s0:
      dhcp-identifier: mac
      dhcp4: true
    enp2s0:
      dhcp-identifier: mac      
      dhcp4: true
    toDKST:
      dhcp4: false
      addresses: [192.168.5.99/24]
  version: 2
